<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-GTA19E4Q" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2020-08-23T17:50:23 CEST" time="0.102" errors="0">
  <testcase name="test2" time="0.016" classname="retryFailedTc.RetryFailedTestDemo"/>
  <testcase name="test3" time="0.007" classname="retryFailedTc.RetryFailedTestDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryFailedTc.RetryFailedTestDemo.test3(RetryFailedTestDemo.java:22)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="retryFailedTc.RetryFailedTestDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
